---
kind: Namespace
apiVersion: v1
metadata:
  name: demo-echo
  generateName: demo-echo
  labels:
    name: demo-echo
    purpose: "API_Gateway_Test"
  annotations:
    describe: "be used in API Gateway test"
status:
  phase: ''
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-echo
  namespace: demo-echo
spec:
  rules:
  - host: echo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: demo-echo
spec:
#  type: ClusterIP
  type: NodePort
  ports:
  - name: echo
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: echo
---
apiVersion: apps/v1beta1  #1.8 v1beta1
kind: Deployment
metadata:
  name: echo
  namespace: demo-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        name: echo
        app: echo
    spec:
      containers:
      - name: echo
        image: mirrorgooglecontainers/echoserver:1.8
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 0.1
            memory: 32Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          runAsNonRoot: false
        stdin: false
        stdinOnce: false
        tty: false
      - name: sshproxy
        image: lijiaocn/sshproxy:1.0
        env:
        - name: ROOTPASS
          value: '123456'
        resources:
          limits:
            cpu: 2
            memory: 128Mi
          requests:
            cpu: 0.1
            memory: 32Mi
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 5
          timeoutSeconds: 5
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          runAsNonRoot: false
        stdin: false
        stdinOnce: false
        tty: false
      restartPolicy: Always
      dnsPolicy: Default
      serviceAccountName: default
      hostNetwork: false
      hostPID: false
      hostIPC: false
